on block place:
  {Bubble.Scaffold} is true
  if {Bubble.Diable} is set:
    stop
  #SCAFFOLD
  if {%player's uuid%.bubble.teleport} is true:
    stop
  else:
    set {_b} to block under player
    set {_b} to block under {_b}
    if {_b} is not air:
      stop
    else:
      if block under event-block is not air:
        stop
      else:
        if player's gamemode is not creative or spectator:
          if {%player's uuid%.bubble.bypass} is not set:
            if {%player's uuid%.bubble.scaffold.cooldown} is not set:
              set {%player's uuid%.bubble.scaffold.cooldown} to true
              set {_loc} to player's location
              if y coordinate of event-block < y coordinate of player:
                if player's pitch is between 9 and -90:
                  teleport player to {_loc}
                  add 1 to {%player's uuid%.bubble}
                  add 1 to {bubble.detections}
                  send "{@Prefix} &4%player% &7is using &6Scaffold&7! &8[&e%{%player's uuid%.bubble}%&8]" to all players where [player input has permission "{@Warn}"]
                  teleport player to {_loc}
                  if {%player's uuid%.bubble.cheat::*} doesn't contain "Scaffold":
                    add "Scaffold" to {%player's uuid%.bubble.cheat::*}
                else:
                  set {%player's uuid%.bubble.old.pitch.time} to {%player's uuid%.bubble.new.pitch.time}
                  set {%player's uuid%.bubble.old.pitch} to {%player's uuid%.bubble.new.pitch}
                  set {%player's uuid%.bubble.new.pitch} to player's pitch
                  set {%player's uuid%.bubble.new.pitch.time} to now
                  set {_dif.time} to difference between {%player's uuid%.bubble.old.pitch.time} and {%player's uuid%.bubble.new.pitch.time}
                  set {_dif.pitch} to difference between {%player's uuid%.bubble.old.pitch} and {%player's uuid%.bubble.new.pitch}
                  if {_dif.time} <= 0.3 seconds:
                    if {_dif.pitch} <= 2.5:
                      add 1 to {%player's uuid%.bubble}
                      add 1 to {bubble.detections}
                      send "{@Prefix} &4%player% &7is using &6Scaffold&7! &8[&e%{%player's uuid%.bubble}%&8]" to all players where [player input has permission "{@Warn}"]
                      teleport player to {_loc}
                      if {%player's uuid%.bubble.cheat::*} doesn't contain "Scaffold":
                        add "Scaffold" to {%player's uuid%.bubble.cheat::*}
                  if {_dif.time} = 0 seconds:
                    send "{@Prefix} &4%player% &7is using &6Speed&7! &8[&e%{%player's uuid%.bubble}%&8]" to all players where [player input has permission "{@Warn}"]
                    teleport player to {_loc}
                    if {%player's uuid%.bubble.cheat::*} doesn't contain "Speed":
                      add "Speed" to {%player's uuid%.bubble.cheat::*}
              delete {%player's uuid%.bubble.scaffold.cooldown}